org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8 -XX:+UseParallelGC
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn
org.gradle.daemon=true
org.gradle.parallel=true

android.nonTransitiveRClass=true
android.useAndroidX=true
android.suppressUnsupportedCompileSdk=37
# AGP 9 compatibility for single-module KMP application layout
android.builtInKotlin=false
android.newDsl=false

kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M
kotlin.native.ignoreDisabledTargets=true
