package com.abbeysbite.app.core.config

/**
 * Canonical legal/policy content, bundled in-app so the screens are always
 * genuine and functional. The same source text lives in `legal/` at the repo
 * root as HTML for hosting; once hosted, the `*_URL` config values point
 * there and the app offers "open in browser" alongside the in-app text.
 */
object LegalContent {

    enum class Kind(val title: String) {
        PRIVACY("Privacy Policy"),
        TERMS("Terms of Service"),
        GUIDELINES("Community Guidelines"),
    }

    fun body(kind: Kind): String = when (kind) {
        Kind.PRIVACY -> PRIVACY
        Kind.TERMS -> TERMS
        Kind.GUIDELINES -> GUIDELINES
    }

    fun hostedUrl(kind: Kind): String? = when (kind) {
        Kind.PRIVACY -> AppSecrets.privacyPolicyUrl
        Kind.TERMS -> AppSecrets.termsUrl
        Kind.GUIDELINES -> AppSecrets.communityGuidelinesUrl
    }.takeIf { it.isNotBlank() && it != "PENDING" }

    val supportUrl: String? =
        AppSecrets.supportUrl.takeIf { it.isNotBlank() && it != "PENDING" }

    private val PRIVACY = """
Abbey's Bite Privacy Policy

Last updated: September 2026

Abbey's Bite helps you make meals you already love more satisfying. Privacy is a design principle, not an afterthought.

WHAT STAYS ON YOUR PHONE
• Meal photos you analyze are processed by an AI model that runs entirely on your device. Analysis photos and your assistant conversations are not sent to our servers or to any AI provider.
• Photos you choose to save to your Journal are stored privately in your account and are visible only to you.

WHAT WE STORE IN YOUR ACCOUNT
• Account basics: email address, username, display name, optional avatar and bio.
• Your preferences: dietary preference, foods you avoid, cooking setup, pantry items.
• Journal entries you save: meal name, date, your notes, and the nutrition summary produced on your device.
• Community content you publish: recipes, likes, saves, reports.
• Friend relationships and the specific progress stats you explicitly choose to share.
• Subscription state (managed by RevenueCat using your account id — we never see your payment details).

WHAT FRIENDS CAN SEE
Nothing, until you opt in. Progress sharing is off by default, per-stat, and never includes meal photos, conversations, notes, or foods you avoid.

ANALYTICS
We record coarse product events (for example "meal scan completed") with no meal content, no photos, and no conversation text.

NOTIFICATIONS
If you enable them, we use OneSignal to deliver pushes for the categories you turn on. Your account id is used so notifications reach the right person.

ADVERTISING
Free accounts see a small number of sponsored cards in the Community feed, served by Google AdMob. Premium removes ads entirely. We never use your meal data to target ads.

DELETING YOUR DATA
Delete your account any time from You → Delete account. This permanently removes your profile, journal, photos, recipes, relationships and conversations from our systems.

CONTACT
Questions about privacy: use You → Help & support.
""".trimIndent()

    private val TERMS = """
Abbey's Bite Terms of Service

Last updated: September 2026

1. THE SERVICE
Abbey's Bite offers meal understanding, practical food suggestions, a food journal and a recipe community. Nutrition information is approximate, generated by on-device AI, and is not medical, dietary or allergy advice. Always verify ingredients yourself — especially for allergies.

2. YOUR ACCOUNT
You're responsible for your account and for keeping your password safe. You must be at least 13 (or the digital-consent age where you live).

3. YOUR CONTENT
Recipes and other content you publish remain yours. By publishing you give us a license to display them within the app. Don't publish content you don't have rights to.

4. COMMUNITY RULES
Follow the Community Guidelines. We may remove content or restrict accounts that break them.

5. SUBSCRIPTIONS
Premium is an auto-renewing subscription billed through your app store (Google Play or Samsung Galaxy Store). Cancel anytime in your store's subscription settings; access continues to the end of the billing period. Refunds follow your store's policy.

6. THE AI ASSISTANT
The assistant runs on your device and can be wrong. Suggestions are ideas, not instructions. Use your own judgment, particularly around allergies and food safety.

7. DISCLAIMERS
The service is provided "as is". To the maximum extent permitted by law we disclaim warranties and limit our liability to the amount you paid us in the past 12 months.

8. CHANGES
We may update these terms; material changes will be announced in-app. Continued use after changes means acceptance.
""".trimIndent()

    private val GUIDELINES = """
Abbey's Bite Community Guidelines

Hidden Gems is a warm corner of the internet for real food from real kitchens. Keep it that way:

BE GENEROUS
Share recipes you actually make. Simple is welcome — a five-minute upgrade helps more people than a showpiece.

BE KIND
No shaming anyone's food, body, budget or kitchen. We don't do "good foods" and "bad foods" here.

BE HONEST
No stolen recipes or images. Credit where credit is due. No spam, ads or self-promotion outside your own recipes.

BE SAFE
No dangerous food-safety advice. Flag allergens where you can, and never present nutrition claims as medical advice.

REPORTING
See something that doesn't belong? Use Report on any recipe or profile. Repeated or serious violations lead to content removal or account restrictions.
""".trimIndent()
}
